# Generated by Django 5.1.7 on 2025-06-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postcategory_category_alter_postcategory_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_anonymous',
        ),
        migrations.AddField(
            model_name='comment',
            name='anonymity',
            field=models.BooleanField(default=False),
        ),
    ]
