# Generated by Django 5.1.7 on 2025-04-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ContactInfo',
        ),
    ]
